server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application.name: climacode-api

weather-sources:
  base-map-url: https://basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}@2x.png
  base-map-zoom-level: 9 # The "z" part of the base tile, bigger zoom = smaller area. Must be equal or greater than any tile radar zoom-level.
  base-map-size: 512 # The pixel size of the base tile image, with the assumption that tiles are squares
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
  tile-radars:
    - name: xxx Radar
      imagery:
        - name: Forecast 15 minutes
          url: https://maps-api-cdn.xxx.com/v1/tiles/radar_eu/{timestamp}_FCST015/{z}/{x}/{y}.png?apikey=xxx
          method: GET
          body: ""
          body-content-type: ""
        - name: Forecast 30 minutes
          url: https://maps-api-cdn.xxx.com/v1/tiles/radar_eu/{timestamp}_FCST030/{z}/{x}/{y}.png?apikey=xxx
          method: GET
          body: ""
          body-content-type: ""
      zoom-level: 6 # The "z" part of the tile to retrieve, bigger = more accurate
      opacity: 0.7 # The opacity to use when this tile will be drawn on top of the base map 0=transparent, 1=opaque
      size: 512 # The pixel size of the radar tile image, with the assumption that tiles are squares
      pixel-tolerance-radius: 5 # When someone requests the nowcast for a coordinate, this is the radius around the coordinate's pixel on the radar image checked for "areaMatch"
      headers:
        referer: "https://www.xxx.com/"
      # templates it's a key-value list of SpEL expressions that get evaluated and replaced on the url and body.
      # key: the string that gets searched to be replaced on the url/body.
      #       for example the key "timestamp" will search and replace "{timestamp}" on the url/body with value.
      # value: the SpEL expression that gets evaluated and put in the place of key.
      templates:
        timestamp : "T(java.time.LocalDateTime).now(T(java.time.ZoneOffset).UTC).minusMinutes(25).withMinute(T(java.lang.Math).min(59, T(java.lang.Math).toIntExact(T(java.lang.Math).round(T(java.time.LocalDateTime).now(T(java.time.ZoneOffset).UTC).minusMinutes(25).getMinute() / 5.0) * 5))).format(T(java.time.format.DateTimeFormatter).ofPattern('yyyyMMdd/yyyyMMdd_HHmm'))"
      legend:
        "#f98000": hail
        "#e13d54": storm-4
        "#d306e0": storm-3
        "#9c1ce0": storm-2
        "#6a30e0": storm-1
        "#4e3be0": storm-0
        "#0c56e0": rain-4
        "#0874dc": rain-3
        "#0a92d8": rain-2
        "#0ca9d4": rain-1
        "#0ebdd2": rain-0
        "#74dbe5": cloudy


  web-scrapers:
    user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
    meteoblue:
      enabled: true
      forecasts:
        - name: Forecast Today
          url: https://www.meteoblue.com/en/weather/week/{longitude}N{latitude}E
          timeframe:  TODAY
        - name: Forecast Tomorrow
          url: https://www.meteoblue.com/en/weather/week/{longitude}N{latitude}E?day=2
          timeframe: TOMORROW
      legend:
        # the actual value is surrounded with square brakets to preserve spaces and special characters
        "[Clear, cloudless sky]": clear
        "[Clear, few cirrus]": clear
        "[Clear with cirrus]": clear
        "[Clear with few low clouds]": clear
        "[Clear with few low clouds and few cirrus]": clear
        "[Clear with few low clouds and cirrus]": clear
        "[Clear but hazy]": clear
        "[Clear but hazy with few cirrus]": clear
        "[Clear but hazy with cirrus]": clear
        "[Partly cloudy]": cloudy
        "[Partly cloudy and few cirrus]": cloudy
        "[Partly cloudy and cirrus]": cloudy
        "[Fog/low stratus clouds]": cloudy
        "[Mixed with some thunderstorm clouds possible]": cloudy
        "[Mixed with few cirrus with some thunderstorm clouds possible]": cloudy
        "[Mixed with cirrus with some thunderstorm clouds possible]": cloudy
        "[Mixed with cirrus and some thunderstorm clouds possible]": cloudy
        "[Fog/low stratus clouds with few cirrus]": cloudy
        "[Fog/low stratus clouds with cirrus]": cloudy
        "[Mostly cloudy]": cloudy
        "[Mostly cloudy and few cirrus]": cloudy
        "[Mostly cloudy and cirrus]": cloudy
        "[Overcast]": cloudy
        "[Mixed with snow showers]": snow-0
        "[Overcast with light snow]": snow-1
        "[Overcast with mixture of snow and rain]": snow-1
        "[Overcast with snow]": snow-2
        "[Overcast with heavy snow]": snow-3
        "[Mixed with showers]": rain-0
        "[Overcast with light rain]": rain-1
        "[Overcast with rain]": rain-2
        "[Overcast with heavy rain]": rain-3
        "[Light rain, thunderstorms likely]": storm-0
        "[Rain, thunderstorms likely]": storm-1
        "[Heavy rain, thunderstorms likely]": storm-2
        "[Storm with heavy snow]": storm-3
    meteociel:
      enabled: true
      geolocation-method: POST
      geolocation-content-type: application/x-www-form-urlencoded
      geolocation-url: https://www.meteociel.fr/temps-reel/lieuhelper.php
      geolocation-body: mode=loc&lon={longitude}&lat={latitude}
      forecasts:
        - name: Forecast GFS
          url: https://www.meteociel.fr/previsions/{location-id}/forecast.htm
          timeframe: MULTIPLE_DAYS
      legend:
        # the actual value is surrounded with square brakets to preserve spaces and special characters
        "[Ensoleillé]": clear
        "[Ciel clair]": clear #
        "[Voilé]": clear #
        "[Peu nuageux]": clear #
        "[Brumeux ou brouillard]": cloudy #
        "[Mitigé]": cloudy #
        "[Nuageux]": cloudy
        "[Couvert]": cloudy #
        "[Averses de pluie faibles]": rain-0 #
        "[Pluie faible]": rain-0 #
        "[Pluie forte]": rain-1
        "[Pluie]": rain-2
        "[Averses de neige]": snow-0
        "[Pluie et neige mêlées]": snow-1
        "[Averse de pluie et neige mêlées]": snow-1
        "[Neige]": snow-2
        "[Risque d'orage faible]": storm-1
        "[Risque d'orage fort]": storm-2
        "[Risque de chute de grêles]": hail